import {
  UnsplashImageListInfo,
  UpsplashImageDetailed,
} from "@/api/gallery/types";

export const MOCK_UNSPLASH_DETAILED: UpsplashImageDetailed = {
  id: "XmKxbgRc-bs",
  slug: "a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
  alternative_slugs: {
    en: "a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
    es: "una-persona-sostiene-un-microdispositivo-en-la-mano-XmKxbgRc-bs",
    ja: "人がマイクロデバイスを手に持っています-XmKxbgRc-bs",
    fr: "une-personne-tient-un-micro-appareil-dans-sa-main-XmKxbgRc-bs",
    it: "una-persona-tiene-in-mano-un-micro-dispositivo-XmKxbgRc-bs",
    ko: "한-사람이-손에-마이크로-장치를-들고-있습니다-XmKxbgRc-bs",
    de: "eine-person-halt-ein-mikrogerat-in-der-hand-XmKxbgRc-bs",
    pt: "uma-pessoa-esta-segurando-um-micro-dispositivo-na-mao-XmKxbgRc-bs",
  },
  created_at: "2024-07-03T23:17:57Z",
  updated_at: "2024-12-28T23:05:55Z",
  promoted_at: null,
  width: 4000,
  height: 6000,
  color: "#264073",
  blur_hash: "LNH1oN~TXmt65t?Z$%NHENEL-oxG",
  description: null,
  alt_description: "A person is holding a micro device in their hand",
  breadcrumbs: [],
  urls: {
    raw: "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8&ixlib=rb-4.0.3",
    full: "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8&ixlib=rb-4.0.3&q=85",
    regular:
      "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8&ixlib=rb-4.0.3&q=80&w=1080",
    small:
      "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8&ixlib=rb-4.0.3&q=80&w=400",
    thumb:
      "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8&ixlib=rb-4.0.3&q=80&w=200",
    small_s3:
      "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1720048171209-71f6fc3d7ea4",
  },
  links: {
    self: "https://api.unsplash.com/photos/a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
    html: "https://unsplash.com/photos/a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
    download:
      "https://unsplash.com/photos/XmKxbgRc-bs/download?ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8",
    download_location:
      "https://api.unsplash.com/photos/XmKxbgRc-bs/download?ixid=M3w2OTEyNDN8MHwxfGFsbHx8fHx8fHx8fDE3MzU0ODg5NjR8",
  },
  likes: 88,
  liked_by_user: false,
  current_user_collections: [],
  sponsorship: {
    impression_urls: [
      "https://secure.insightexpressai.com/adServer/adServerESI.aspx?script=false&bannerID=12236441&rnd=[timestamp]&redir=https://secure.insightexpressai.com/adserver/1pixel.gif",
    ],
    tagline: "Memory for every endeavor",
    tagline_url: "https://www.samsung.com/us/memory-storage/",
    sponsor: {
      id: "eySMK9KwmJU",
      updated_at: "2024-12-28T16:05:38Z",
      username: "samsungmemory",
      name: "Samsung Memory",
      first_name: "Samsung",
      last_name: "Memory",
      twitter_username: "SamsungSemiUS",
      portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
      bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/samsungmemory",
        html: "https://unsplash.com/@samsungmemory",
        photos: "https://api.unsplash.com/users/samsungmemory/photos",
        likes: "https://api.unsplash.com/users/samsungmemory/likes",
        portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
        following: "https://api.unsplash.com/users/samsungmemory/following",
        followers: "https://api.unsplash.com/users/samsungmemory/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "samsungsemiconductor",
      total_collections: 1,
      total_likes: 0,
      total_photos: 880,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "samsungsemiconductor",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        twitter_username: "SamsungSemiUS",
        paypal_email: null,
      },
    },
  },
  topic_submissions: {},
  asset_type: "photo",
  user: {
    id: "eySMK9KwmJU",
    updated_at: "2024-12-28T16:05:38Z",
    username: "samsungmemory",
    name: "Samsung Memory",
    first_name: "Samsung",
    last_name: "Memory",
    twitter_username: "SamsungSemiUS",
    portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
    bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
    location: null,
    links: {
      self: "https://api.unsplash.com/users/samsungmemory",
      html: "https://unsplash.com/@samsungmemory",
      photos: "https://api.unsplash.com/users/samsungmemory/photos",
      likes: "https://api.unsplash.com/users/samsungmemory/likes",
      portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
      following: "https://api.unsplash.com/users/samsungmemory/following",
      followers: "https://api.unsplash.com/users/samsungmemory/followers",
    },
    profile_image: {
      small:
        "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
      medium:
        "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
      large:
        "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
    },
    instagram_username: "samsungsemiconductor",
    total_collections: 1,
    total_likes: 0,
    total_photos: 880,
    total_promoted_photos: 38,
    total_illustrations: 0,
    total_promoted_illustrations: 0,
    accepted_tos: true,
    for_hire: false,
    social: {
      instagram_username: "samsungsemiconductor",
      portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
      twitter_username: "SamsungSemiUS",
      paypal_email: null,
    },
  },
  exif: {
    make: "SONY",
    model: "ILCE-7M3",
    name: "SONY, ILCE-7M3",
    exposure_time: "1/125",
    aperture: "2.8",
    focal_length: "70.0",
    iso: 250,
  },
  location: {
    name: null,
    city: null,
    country: null,
    position: {
      latitude: 0,
      longitude: 0,
    },
  },
  meta: {
    index: true,
  },
  public_domain: false,
  tags: [
    {
      type: "search",
      title: "memory card",
    },
    {
      type: "search",
      title: "microsdcard",
    },
    {
      type: "search",
      title: "electronics",
    },
    {
      type: "search",
      title: "text",
    },
    {
      type: "search",
      title: "computer",
    },
    {
      type: "search",
      title: "cell phone",
    },
    {
      type: "search",
      title: "mobile phone",
    },
    {
      type: "search",
      title: "phone",
    },
  ],
  views: 4300896,
  downloads: 23872,
  topics: [],
};

export const MOCK_UNSPLASH_IMAGE_LIST: UnsplashImageListInfo[] = [
  {
    id: "XmKxbgRc-bs",
    slug: "a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
    alternative_slugs: {
      en: "a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
      es: "una-persona-sostiene-un-microdispositivo-en-la-mano-XmKxbgRc-bs",
      ja: "人がマイクロデバイスを手に持っています-XmKxbgRc-bs",
      fr: "une-personne-tient-un-micro-appareil-dans-sa-main-XmKxbgRc-bs",
      it: "una-persona-tiene-in-mano-un-micro-dispositivo-XmKxbgRc-bs",
      ko: "한-사람이-손에-마이크로-장치를-들고-있습니다-XmKxbgRc-bs",
      de: "eine-person-halt-ein-mikrogerat-in-der-hand-XmKxbgRc-bs",
      pt: "uma-pessoa-esta-segurando-um-micro-dispositivo-na-mao-XmKxbgRc-bs",
    },
    created_at: "2024-07-03T23:17:57Z",
    updated_at: "2024-12-28T23:05:55Z",
    promoted_at: null,
    width: 4000,
    height: 6000,
    color: "#264073",
    blur_hash: "LNH1oN~TXmt65t?Z$%NHENEL-oxG",
    description: null,
    alt_description: "A person is holding a micro device in their hand",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1720048171209-71f6fc3d7ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1720048171209-71f6fc3d7ea4",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
      html: "https://unsplash.com/photos/a-person-is-holding-a-micro-device-in-their-hand-XmKxbgRc-bs",
      download:
        "https://unsplash.com/photos/XmKxbgRc-bs/download?ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/XmKxbgRc-bs/download?ixid=M3w2OTEyNDN8MXwxfGFsbHwxfHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 87,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: {
      impression_urls: [
        "https://secure.insightexpressai.com/adServer/adServerESI.aspx?script=false&bannerID=12236441&rnd=[timestamp]&redir=https://secure.insightexpressai.com/adserver/1pixel.gif",
      ],
      tagline: "Memory for every endeavor",
      tagline_url: "https://www.samsung.com/us/memory-storage/",
      sponsor: {
        id: "eySMK9KwmJU",
        updated_at: "2024-12-28T16:05:38Z",
        username: "samsungmemory",
        name: "Samsung Memory",
        first_name: "Samsung",
        last_name: "Memory",
        twitter_username: "SamsungSemiUS",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
        location: null,
        links: {
          self: "https://api.unsplash.com/users/samsungmemory",
          html: "https://unsplash.com/@samsungmemory",
          photos: "https://api.unsplash.com/users/samsungmemory/photos",
          likes: "https://api.unsplash.com/users/samsungmemory/likes",
          portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
          following: "https://api.unsplash.com/users/samsungmemory/following",
          followers: "https://api.unsplash.com/users/samsungmemory/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "samsungsemiconductor",
        total_collections: 1,
        total_likes: 0,
        total_photos: 880,
        total_promoted_photos: 38,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "samsungsemiconductor",
          portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
          twitter_username: "SamsungSemiUS",
          paypal_email: null,
        },
      },
    },
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "eySMK9KwmJU",
      updated_at: "2024-12-28T16:05:38Z",
      username: "samsungmemory",
      name: "Samsung Memory",
      first_name: "Samsung",
      last_name: "Memory",
      twitter_username: "SamsungSemiUS",
      portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
      bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/samsungmemory",
        html: "https://unsplash.com/@samsungmemory",
        photos: "https://api.unsplash.com/users/samsungmemory/photos",
        likes: "https://api.unsplash.com/users/samsungmemory/likes",
        portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
        following: "https://api.unsplash.com/users/samsungmemory/following",
        followers: "https://api.unsplash.com/users/samsungmemory/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "samsungsemiconductor",
      total_collections: 1,
      total_likes: 0,
      total_photos: 880,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "samsungsemiconductor",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        twitter_username: "SamsungSemiUS",
        paypal_email: null,
      },
    },
  },
  {
    id: "ZJk8NX0aR8s",
    slug: "a-close-up-of-a-white-object-with-a-white-background-ZJk8NX0aR8s",
    alternative_slugs: {
      en: "a-close-up-of-a-white-object-with-a-white-background-ZJk8NX0aR8s",
      es: "un-primer-plano-de-un-objeto-blanco-con-un-fondo-blanco-ZJk8NX0aR8s",
      ja: "白い背景の白いオブジェクトのクローズアップ-ZJk8NX0aR8s",
      fr: "un-gros-plan-dun-objet-blanc-avec-un-fond-blanc-ZJk8NX0aR8s",
      it: "un-primo-piano-di-un-oggetto-bianco-con-uno-sfondo-bianco-ZJk8NX0aR8s",
      ko: "흰색-배경의-흰색-물체를-클로즈업한-것입니다-ZJk8NX0aR8s",
      de: "nahaufnahme-eines-weissen-objekts-mit-weissem-hintergrund-ZJk8NX0aR8s",
      pt: "um-close-up-de-um-objeto-branco-com-um-fundo-branco-ZJk8NX0aR8s",
    },
    created_at: "2024-11-02T15:55:37Z",
    updated_at: "2024-12-29T14:30:38Z",
    promoted_at: "2024-12-29T00:22:00Z",
    width: 8400,
    height: 5600,
    color: "#d9d9d9",
    blur_hash: "LIMk9Jt7~qIURjofxuWBt7RjRPof",
    description: null,
    alt_description: "A close up of a white object with a white background",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1730562885841-0163ae9eeca9?ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1730562885841-0163ae9eeca9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1730562885841-0163ae9eeca9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1730562885841-0163ae9eeca9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1730562885841-0163ae9eeca9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1730562885841-0163ae9eeca9",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-white-object-with-a-white-background-ZJk8NX0aR8s",
      html: "https://unsplash.com/photos/a-close-up-of-a-white-object-with-a-white-background-ZJk8NX0aR8s",
      download:
        "https://unsplash.com/photos/ZJk8NX0aR8s/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/ZJk8NX0aR8s/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwyfHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 54,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "3d-renders": {
        status: "approved",
        approved_on: "2024-11-08T09:40:19Z",
      },
      "textures-patterns": {
        status: "approved",
        approved_on: "2024-11-03T08:11:15Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "ogQykx6hk_c",
      updated_at: "2024-12-28T17:39:31Z",
      username: "pawel_czerwinski",
      name: "Pawel Czerwinski",
      first_name: "Pawel",
      last_name: "Czerwinski",
      twitter_username: "pm_cze",
      portfolio_url: "http://paypal.me/pmcze",
      bio: "Questions about how you can use the photos? help.unsplash.com/en/collections/1463188-unsplash-license 👍",
      location: "Poland",
      links: {
        self: "https://api.unsplash.com/users/pawel_czerwinski",
        html: "https://unsplash.com/@pawel_czerwinski",
        photos: "https://api.unsplash.com/users/pawel_czerwinski/photos",
        likes: "https://api.unsplash.com/users/pawel_czerwinski/likes",
        portfolio: "https://api.unsplash.com/users/pawel_czerwinski/portfolio",
        following: "https://api.unsplash.com/users/pawel_czerwinski/following",
        followers: "https://api.unsplash.com/users/pawel_czerwinski/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1592328433409-d9ce8a5333eaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1592328433409-d9ce8a5333eaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1592328433409-d9ce8a5333eaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "pmcze",
      total_collections: 7,
      total_likes: 44934,
      total_photos: 2319,
      total_promoted_photos: 2075,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "pmcze",
        portfolio_url: "http://paypal.me/pmcze",
        twitter_username: "pm_cze",
        paypal_email: null,
      },
    },
  },
  {
    id: "MXdN_hoGK6M",
    slug: "a-man-standing-on-a-sidewalk-wearing-a-leather-jacket-MXdN_hoGK6M",
    alternative_slugs: {
      en: "a-man-standing-on-a-sidewalk-wearing-a-leather-jacket-MXdN_hoGK6M",
      es: "un-hombre-de-pie-en-una-acera-con-una-chaqueta-de-cuero-MXdN_hoGK6M",
      ja: "革ジャンを着て歩道に立つ男性-MXdN_hoGK6M",
      fr: "un-homme-debout-sur-un-trottoir-portant-une-veste-en-cuir-MXdN_hoGK6M",
      it: "un-uomo-in-piedi-su-un-marciapiede-indossa-uno-giacca-di-pelle-MXdN_hoGK6M",
      ko: "가죽-재킷을-입고-보도에-서-있는-남자-MXdN_hoGK6M",
      de: "ein-mann-der-mit-einer-lederjacke-auf-einem-burgersteig-steht-MXdN_hoGK6M",
      pt: "um-homem-em-pe-em-uma-calcada-vestindo-uma-jaqueta-de-couro-MXdN_hoGK6M",
    },
    created_at: "2024-11-07T23:28:07Z",
    updated_at: "2024-12-29T03:14:21Z",
    promoted_at: "2024-12-29T00:21:00Z",
    width: 1933,
    height: 2900,
    color: "#d9c0a6",
    blur_hash: "LOJaW9%2~TWB4:WBNGoeM{xZE2WC",
    description: null,
    alt_description: "A man standing on a sidewalk wearing a leather jacket",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1731021347639-8aac941f5e29?ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1731021347639-8aac941f5e29?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1731021347639-8aac941f5e29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1731021347639-8aac941f5e29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1731021347639-8aac941f5e29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1731021347639-8aac941f5e29",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-man-standing-on-a-sidewalk-wearing-a-leather-jacket-MXdN_hoGK6M",
      html: "https://unsplash.com/photos/a-man-standing-on-a-sidewalk-wearing-a-leather-jacket-MXdN_hoGK6M",
      download:
        "https://unsplash.com/photos/MXdN_hoGK6M/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/MXdN_hoGK6M/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwzfHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 31,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "fashion-beauty": {
        status: "approved",
        approved_on: "2024-11-08T08:17:32Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "X70Bvq50oiM",
      updated_at: "2024-12-28T02:48:17Z",
      username: "itsbrunoagain",
      name: "Bruno Ngarukiye",
      first_name: "Bruno",
      last_name: "Ngarukiye",
      twitter_username: null,
      portfolio_url: null,
      bio: "Paris based portrait and fashion photographer.\r\nGrateful for every donations, no matter at what level.   www.brunoagain.com",
      location: "Paris",
      links: {
        self: "https://api.unsplash.com/users/itsbrunoagain",
        html: "https://unsplash.com/@itsbrunoagain",
        photos: "https://api.unsplash.com/users/itsbrunoagain/photos",
        likes: "https://api.unsplash.com/users/itsbrunoagain/likes",
        portfolio: "https://api.unsplash.com/users/itsbrunoagain/portfolio",
        following: "https://api.unsplash.com/users/itsbrunoagain/following",
        followers: "https://api.unsplash.com/users/itsbrunoagain/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1729379101371-f4e72deb8dc8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1729379101371-f4e72deb8dc8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1729379101371-f4e72deb8dc8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "itsbrunoagain",
      total_collections: 0,
      total_likes: 25,
      total_photos: 201,
      total_promoted_photos: 11,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "itsbrunoagain",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "BHzvURQjepc",
    slug: "a-man-standing-in-the-middle-of-a-snow-covered-field-BHzvURQjepc",
    alternative_slugs: {
      en: "a-man-standing-in-the-middle-of-a-snow-covered-field-BHzvURQjepc",
      es: "un-hombre-de-pie-en-medio-de-un-campo-cubierto-de-nieve-BHzvURQjepc",
      ja: "雪原の真ん中に佇む男-BHzvURQjepc",
      fr: "un-homme-debout-au-milieu-dun-champ-enneige-BHzvURQjepc",
      it: "un-uomo-standing-in-mezzo-di-uno-campo-coperto-di-neve-BHzvURQjepc",
      ko: "눈-덮인-들판-한가운데에-서-있는-남자-BHzvURQjepc",
      de: "ein-mann-steht-mitten-auf-einem-schneebedeckten-feld-BHzvURQjepc",
      pt: "um-homem-em-pe-no-meio-de-um-campo-coberto-de-neve-BHzvURQjepc",
    },
    created_at: "2024-11-11T13:08:09Z",
    updated_at: "2024-12-29T12:02:35Z",
    promoted_at: "2024-12-29T00:20:00Z",
    width: 2941,
    height: 3676,
    color: "#c0d9d9",
    blur_hash: "LJI=#|DiNG%M~qo#xaM{R6IUx]t7",
    description: "Juta lake at the winter.",
    alt_description: "A man standing in the middle of a snow covered field",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1731330269319-0f053cd5d74b?ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1731330269319-0f053cd5d74b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1731330269319-0f053cd5d74b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1731330269319-0f053cd5d74b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1731330269319-0f053cd5d74b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1731330269319-0f053cd5d74b",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-man-standing-in-the-middle-of-a-snow-covered-field-BHzvURQjepc",
      html: "https://unsplash.com/photos/a-man-standing-in-the-middle-of-a-snow-covered-field-BHzvURQjepc",
      download:
        "https://unsplash.com/photos/BHzvURQjepc/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/BHzvURQjepc/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw0fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 23,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "7V_7leyExD8",
      updated_at: "2024-12-29T09:34:43Z",
      username: "maksim_taawy",
      name: "Maksim Samuilionak",
      first_name: "Maksim",
      last_name: "Samuilionak",
      twitter_username: null,
      portfolio_url: "https://www.instagram.com/maksim.taawy",
      bio: "Frontend developer, post-rock musician and a little bit photographer.",
      location: "Tbilisi, Georgia",
      links: {
        self: "https://api.unsplash.com/users/maksim_taawy",
        html: "https://unsplash.com/@maksim_taawy",
        photos: "https://api.unsplash.com/users/maksim_taawy/photos",
        likes: "https://api.unsplash.com/users/maksim_taawy/likes",
        portfolio: "https://api.unsplash.com/users/maksim_taawy/portfolio",
        following: "https://api.unsplash.com/users/maksim_taawy/following",
        followers: "https://api.unsplash.com/users/maksim_taawy/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1727426919507-c42e554b6e67image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1727426919507-c42e554b6e67image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1727426919507-c42e554b6e67image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "maksim.taawy",
      total_collections: 0,
      total_likes: 23,
      total_photos: 73,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "maksim.taawy",
        portfolio_url: "https://www.instagram.com/maksim.taawy",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "Xmz1HLjTrE8",
    slug: "the-statue-of-liberty-is-holding-a-bird-in-its-hand-Xmz1HLjTrE8",
    alternative_slugs: {
      en: "the-statue-of-liberty-is-holding-a-bird-in-its-hand-Xmz1HLjTrE8",
      es: "la-estatua-de-la-libertad-sostiene-un-pajaro-en-la-mano-Xmz1HLjTrE8",
      ja: "自由の女神は手に鳥を持っています-Xmz1HLjTrE8",
      fr: "la-statue-de-la-liberte-tient-un-oiseau-dans-sa-main-Xmz1HLjTrE8",
      it: "la-statua-della-liberta-tiene-in-mano-un-uccello-Xmz1HLjTrE8",
      ko: "자유의-여신상은-손에-새를-들고-있습니다-Xmz1HLjTrE8",
      de: "die-freiheitsstatue-halt-einen-vogel-in-der-hand-Xmz1HLjTrE8",
      pt: "a-estatua-da-liberdade-esta-segurando-um-passaro-na-mao-Xmz1HLjTrE8",
    },
    created_at: "2024-11-11T14:15:28Z",
    updated_at: "2024-12-29T12:39:37Z",
    promoted_at: "2024-12-29T00:18:00Z",
    width: 4000,
    height: 6000,
    color: "#8ca6a6",
    blur_hash: "LPF?nX_ND+NGJ:Mxxtt8kDaxV@ay",
    description: null,
    alt_description: "The statue of liberty is holding a bird in its hand",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1731331131233-4f73c93ae693?ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1731331131233-4f73c93ae693?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1731331131233-4f73c93ae693?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1731331131233-4f73c93ae693?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1731331131233-4f73c93ae693?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1731331131233-4f73c93ae693",
    },
    links: {
      self: "https://api.unsplash.com/photos/the-statue-of-liberty-is-holding-a-bird-in-its-hand-Xmz1HLjTrE8",
      html: "https://unsplash.com/photos/the-statue-of-liberty-is-holding-a-bird-in-its-hand-Xmz1HLjTrE8",
      download:
        "https://unsplash.com/photos/Xmz1HLjTrE8/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/Xmz1HLjTrE8/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw1fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 72,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      travel: {
        status: "approved",
        approved_on: "2024-11-12T09:22:46Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "yoxKVnVPgsw",
      updated_at: "2024-12-22T06:29:58Z",
      username: "ismajn",
      name: "Ismaël Jean",
      first_name: "Ismaël",
      last_name: "Jean",
      twitter_username: null,
      portfolio_url: null,
      bio: "🖼 Framing life\r\n⛰️ Mountains, Music & Memories",
      location: "Paris, France",
      links: {
        self: "https://api.unsplash.com/users/ismajn",
        html: "https://unsplash.com/@ismajn",
        photos: "https://api.unsplash.com/users/ismajn/photos",
        likes: "https://api.unsplash.com/users/ismajn/likes",
        portfolio: "https://api.unsplash.com/users/ismajn/portfolio",
        following: "https://api.unsplash.com/users/ismajn/following",
        followers: "https://api.unsplash.com/users/ismajn/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1728412140076-b7111e4648c7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1728412140076-b7111e4648c7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1728412140076-b7111e4648c7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "ismael.jean",
      total_collections: 0,
      total_likes: 8,
      total_photos: 59,
      total_promoted_photos: 12,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "ismael.jean",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "8FBr3z73Ymw",
    slug: "a-snowboarder-is-doing-a-trick-in-the-air-8FBr3z73Ymw",
    alternative_slugs: {
      en: "a-snowboarder-is-doing-a-trick-in-the-air-8FBr3z73Ymw",
      es: "un-snowboarder-esta-haciendo-un-truco-en-el-aire-8FBr3z73Ymw",
      ja: "スノーボーダーが空中でトリックをしている-8FBr3z73Ymw",
      fr: "un-snowboarder-fait-un-tour-dans-les-airs-8FBr3z73Ymw",
      it: "uno-snowboarder-sta-facendo-un-trick-in-aria-8FBr3z73Ymw",
      ko: "스노우-보더가-공중에서-트릭을하고-있습니다-8FBr3z73Ymw",
      de: "ein-snowboarder-macht-einen-trick-in-der-luft-8FBr3z73Ymw",
      pt: "um-snowboarder-esta-fazendo-um-truque-no-ar-8FBr3z73Ymw",
    },
    created_at: "2024-11-22T15:07:59Z",
    updated_at: "2024-12-29T15:04:40Z",
    promoted_at: "2024-12-29T00:17:00Z",
    width: 4561,
    height: 6842,
    color: "#a6c0c0",
    blur_hash: "LLIYqX4nM|WCu6s:xaWB4otSoft7",
    description: null,
    alt_description: "A snowboarder is doing a trick in the air",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732287931034-c4cc1b06de6a?ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1732287931034-c4cc1b06de6a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1732287931034-c4cc1b06de6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732287931034-c4cc1b06de6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732287931034-c4cc1b06de6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732287931034-c4cc1b06de6a",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-snowboarder-is-doing-a-trick-in-the-air-8FBr3z73Ymw",
      html: "https://unsplash.com/photos/a-snowboarder-is-doing-a-trick-in-the-air-8FBr3z73Ymw",
      download:
        "https://unsplash.com/photos/8FBr3z73Ymw/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/8FBr3z73Ymw/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw2fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 46,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "TP6oaAc99Xc",
      updated_at: "2024-12-29T12:59:02Z",
      username: "martin_masson",
      name: "Martin Masson",
      first_name: "Martin",
      last_name: "Masson",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "France",
      links: {
        self: "https://api.unsplash.com/users/martin_masson",
        html: "https://unsplash.com/@martin_masson",
        photos: "https://api.unsplash.com/users/martin_masson/photos",
        likes: "https://api.unsplash.com/users/martin_masson/likes",
        portfolio: "https://api.unsplash.com/users/martin_masson/portfolio",
        following: "https://api.unsplash.com/users/martin_masson/following",
        followers: "https://api.unsplash.com/users/martin_masson/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1696253320607-743379a797e2?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1696253320607-743379a797e2?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1696253320607-743379a797e2?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "martin.masson_",
      total_collections: 0,
      total_likes: 139,
      total_photos: 63,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "martin.masson_",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "GY3wBBKiDIM",
    slug: "a-woman-sitting-on-a-chair-in-a-dark-room-GY3wBBKiDIM",
    alternative_slugs: {
      en: "a-woman-sitting-on-a-chair-in-a-dark-room-GY3wBBKiDIM",
      es: "una-mujer-sentada-en-una-silla-en-una-habitacion-oscura-GY3wBBKiDIM",
      ja: "暗い部屋で椅子に座る女性-GY3wBBKiDIM",
      fr: "une-femme-assise-sur-une-chaise-dans-une-piece-sombre-GY3wBBKiDIM",
      it: "una-donna-seduta-su-una-sedia-in-una-stanza-buia-GY3wBBKiDIM",
      ko: "어두운-방에서-의자에-앉아있는-여자-GY3wBBKiDIM",
      de: "eine-frau-die-in-einem-dunklen-raum-auf-einem-stuhl-sitzt-GY3wBBKiDIM",
      pt: "uma-mulher-sentada-em-uma-cadeira-em-um-quarto-escuro-GY3wBBKiDIM",
    },
    created_at: "2024-11-22T14:44:03Z",
    updated_at: "2024-12-29T11:36:38Z",
    promoted_at: "2024-12-29T00:16:00Z",
    width: 3425,
    height: 5137,
    color: "#405973",
    blur_hash: "L67_~CRPDOx]Mw.TV@MwNGx^V?Ri",
    description: null,
    alt_description: "A woman sitting on a chair in a dark room",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732286521912-9c48f3faee78?ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1732286521912-9c48f3faee78?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1732286521912-9c48f3faee78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732286521912-9c48f3faee78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732286521912-9c48f3faee78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732286521912-9c48f3faee78",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-woman-sitting-on-a-chair-in-a-dark-room-GY3wBBKiDIM",
      html: "https://unsplash.com/photos/a-woman-sitting-on-a-chair-in-a-dark-room-GY3wBBKiDIM",
      download:
        "https://unsplash.com/photos/GY3wBBKiDIM/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/GY3wBBKiDIM/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw3fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 24,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "fashion-beauty": {
        status: "approved",
        approved_on: "2024-12-17T12:48:26Z",
      },
      people: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "C2014xehYcw",
      updated_at: "2024-12-29T13:49:03Z",
      username: "chilltone",
      name: "Janis Dzenis",
      first_name: "Janis",
      last_name: "Dzenis",
      twitter_username: null,
      portfolio_url: "https://chilltoneph.com/",
      bio: "Passionate and detail-oriented fashion and portrait photographer specializing in studio photography. Expert in crafting striking images with a focus on bold styling, creative lighting, and evocative storytelling.",
      location: "London",
      links: {
        self: "https://api.unsplash.com/users/chilltone",
        html: "https://unsplash.com/@chilltone",
        photos: "https://api.unsplash.com/users/chilltone/photos",
        likes: "https://api.unsplash.com/users/chilltone/likes",
        portfolio: "https://api.unsplash.com/users/chilltone/portfolio",
        following: "https://api.unsplash.com/users/chilltone/following",
        followers: "https://api.unsplash.com/users/chilltone/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1734014188179-c37f7ce4dcceimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1734014188179-c37f7ce4dcceimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1734014188179-c37f7ce4dcceimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "chilltone.ph",
      total_collections: 1,
      total_likes: 50,
      total_photos: 401,
      total_promoted_photos: 54,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "chilltone.ph",
        portfolio_url: "https://chilltoneph.com/",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "UDPqFfA5rgw",
    slug: "a-wooden-door-with-rivets-on-the-side-of-it-UDPqFfA5rgw",
    alternative_slugs: {
      en: "a-wooden-door-with-rivets-on-the-side-of-it-UDPqFfA5rgw",
      es: "una-puerta-de-madera-con-remaches-en-el-lateral-UDPqFfA5rgw",
      ja: "側面にリベットが付いた木製のドア-UDPqFfA5rgw",
      fr: "une-porte-en-bois-avec-des-rivets-sur-le-cote-UDPqFfA5rgw",
      it: "una-porta-di-legno-con-rivetti-sul-lato-UDPqFfA5rgw",
      ko: "측면에-리벳이-있는-나무-문-UDPqFfA5rgw",
      de: "eine-holztur-mit-nieten-an-der-seite-UDPqFfA5rgw",
      pt: "uma-porta-de-madeira-com-rebites-na-lateral-UDPqFfA5rgw",
    },
    created_at: "2024-11-19T12:49:33Z",
    updated_at: "2024-12-29T13:07:55Z",
    promoted_at: "2024-12-29T00:14:00Z",
    width: 3024,
    height: 3778,
    color: "#f3f3f3",
    blur_hash: "L~PF}=?^xaROo#aKfkkCg3ada|kC",
    description: "Vintage wooden door on a blue wall, Mediterranean House",
    alt_description: "A wooden door with rivets on the side of it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732020510324-93da7f20d1e2?ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1732020510324-93da7f20d1e2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1732020510324-93da7f20d1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732020510324-93da7f20d1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732020510324-93da7f20d1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732020510324-93da7f20d1e2",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-wooden-door-with-rivets-on-the-side-of-it-UDPqFfA5rgw",
      html: "https://unsplash.com/photos/a-wooden-door-with-rivets-on-the-side-of-it-UDPqFfA5rgw",
      download:
        "https://unsplash.com/photos/UDPqFfA5rgw/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/UDPqFfA5rgw/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw4fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 25,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "architecture-interior": {
        status: "approved",
        approved_on: "2024-11-20T13:22:49Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "ltIwB8rOxnY",
      updated_at: "2024-12-18T18:13:16Z",
      username: "pixasquare",
      name: "Pixasquare",
      first_name: "Pixasquare",
      last_name: null,
      twitter_username: null,
      portfolio_url: "http://bento.me/pixasquare",
      bio: "Creative Studio for Brand Logos, Web Design + Photography. Free & Premium Digital Products. Check Shop!",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/pixasquare",
        html: "https://unsplash.com/@pixasquare",
        photos: "https://api.unsplash.com/users/pixasquare/photos",
        likes: "https://api.unsplash.com/users/pixasquare/likes",
        portfolio: "https://api.unsplash.com/users/pixasquare/portfolio",
        following: "https://api.unsplash.com/users/pixasquare/following",
        followers: "https://api.unsplash.com/users/pixasquare/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1731941419410-308c47b7bbd2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1731941419410-308c47b7bbd2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1731941419410-308c47b7bbd2image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 17,
      total_likes: 5,
      total_photos: 34,
      total_promoted_photos: 8,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "http://bento.me/pixasquare",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "JFRVI35Szk0",
    slug: "a-man-skiing-down-a-snow-covered-mountain-JFRVI35Szk0",
    alternative_slugs: {
      en: "a-man-skiing-down-a-snow-covered-mountain-JFRVI35Szk0",
      es: "un-hombre-esquiando-por-una-montana-cubierta-de-nieve-JFRVI35Szk0",
      ja: "雪に覆われた山をスキーで滑り降りる男性-JFRVI35Szk0",
      fr: "un-homme-descendant-une-montagne-enneigee-JFRVI35Szk0",
      it: "un-uomo-che-scia-giu-per-una-montagna-coperta-di-neve-JFRVI35Szk0",
      ko: "스키를-타고-눈-덮인-산을-내려오는-남자-JFRVI35Szk0",
      de: "ein-mann-fahrt-einen-schneebedeckten-berg-hinunter-JFRVI35Szk0",
      pt: "um-homem-esquiando-abaixo-de-uma-montanha-coberta-de-neve-JFRVI35Szk0",
    },
    created_at: "2024-11-30T01:09:35Z",
    updated_at: "2024-12-29T15:24:48Z",
    promoted_at: "2024-12-29T00:13:00Z",
    width: 3648,
    height: 5472,
    color: "#a6c0d9",
    blur_hash: "LDJ9DL00IUNI_3t8RjR*r?kCM{of",
    description: null,
    alt_description: "A man skiing down a snow covered mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732928913242-1f58eede0e19?ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1732928913242-1f58eede0e19?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1732928913242-1f58eede0e19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732928913242-1f58eede0e19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732928913242-1f58eede0e19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732928913242-1f58eede0e19",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-man-skiing-down-a-snow-covered-mountain-JFRVI35Szk0",
      html: "https://unsplash.com/photos/a-man-skiing-down-a-snow-covered-mountain-JFRVI35Szk0",
      download:
        "https://unsplash.com/photos/JFRVI35Szk0/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA",
      download_location:
        "https://api.unsplash.com/photos/JFRVI35Szk0/download?ixid=M3w2OTEyNDN8MHwxfGFsbHw5fHx8fHx8fHwxNzM1NDg2NDYwfA",
    },
    likes: 29,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      sports: {
        status: "approved",
        approved_on: "2024-12-04T10:16:08Z",
      },
      travel: {
        status: "approved",
        approved_on: "2024-12-16T09:38:45Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "oHdIYDPpoRM",
      updated_at: "2024-12-27T18:33:06Z",
      username: "martinjernberg",
      name: "Martin Jernberg",
      first_name: "Martin",
      last_name: "Jernberg",
      twitter_username: null,
      portfolio_url: "http://www.martinjernberg.com/",
      bio: null,
      location: "Denver, CO",
      links: {
        self: "https://api.unsplash.com/users/martinjernberg",
        html: "https://unsplash.com/@martinjernberg",
        photos: "https://api.unsplash.com/users/martinjernberg/photos",
        likes: "https://api.unsplash.com/users/martinjernberg/likes",
        portfolio: "https://api.unsplash.com/users/martinjernberg/portfolio",
        following: "https://api.unsplash.com/users/martinjernberg/following",
        followers: "https://api.unsplash.com/users/martinjernberg/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1716438065741-9f2b799b9aedimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "martin.jernberg",
      total_collections: 0,
      total_likes: 30,
      total_photos: 40,
      total_promoted_photos: 34,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "martin.jernberg",
        portfolio_url: "http://www.martinjernberg.com/",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "nlR_q6d97Qk",
    slug: "a-building-with-a-white-awning-next-to-a-street-nlR_q6d97Qk",
    alternative_slugs: {
      en: "a-building-with-a-white-awning-next-to-a-street-nlR_q6d97Qk",
      es: "un-edificio-con-un-toldo-blanco-junto-a-una-calle-nlR_q6d97Qk",
      ja: "通りの隣に白い日よけがある建物-nlR_q6d97Qk",
      fr: "un-batiment-avec-un-auvent-blanc-a-cote-dune-rue-nlR_q6d97Qk",
      it: "un-edificio-con-una-tenda-bianca-accanto-a-una-strada-nlR_q6d97Qk",
      ko: "거리-옆에-흰색-차양이-있는-건물-nlR_q6d97Qk",
      de: "ein-gebaude-mit-weisser-markise-neben-einer-strasse-nlR_q6d97Qk",
      pt: "um-predio-com-um-toldo-branco-ao-lado-de-uma-rua-nlR_q6d97Qk",
    },
    created_at: "2024-11-29T13:52:47Z",
    updated_at: "2024-12-29T15:24:41Z",
    promoted_at: "2024-12-29T00:12:00Z",
    width: 6774,
    height: 4492,
    color: "#c0c0c0",
    blur_hash: "LNI#ohRj4:?b~pofM{WB.8M{IUax",
    description: null,
    alt_description: "A building with a white awning next to a street",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732888329753-0ff89467e6c8?ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1732888329753-0ff89467e6c8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1732888329753-0ff89467e6c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732888329753-0ff89467e6c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732888329753-0ff89467e6c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732888329753-0ff89467e6c8",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-building-with-a-white-awning-next-to-a-street-nlR_q6d97Qk",
      html: "https://unsplash.com/photos/a-building-with-a-white-awning-next-to-a-street-nlR_q6d97Qk",
      download:
        "https://unsplash.com/photos/nlR_q6d97Qk/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw",
      download_location:
        "https://api.unsplash.com/photos/nlR_q6d97Qk/download?ixid=M3w2OTEyNDN8MHwxfGFsbHwxMHx8fHx8fHx8MTczNTQ4NjQ2MHw",
    },
    likes: 15,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "SMyuYswhIIQ",
      updated_at: "2024-12-29T05:30:58Z",
      username: "catpisces",
      name: "Tiange Xiang",
      first_name: "Tiange",
      last_name: "Xiang",
      twitter_username: null,
      portfolio_url: null,
      bio: "No theme defines, no mood constrains",
      location: "Tokyo, Japan",
      links: {
        self: "https://api.unsplash.com/users/catpisces",
        html: "https://unsplash.com/@catpisces",
        photos: "https://api.unsplash.com/users/catpisces/photos",
        likes: "https://api.unsplash.com/users/catpisces/likes",
        portfolio: "https://api.unsplash.com/users/catpisces/portfolio",
        following: "https://api.unsplash.com/users/catpisces/following",
        followers: "https://api.unsplash.com/users/catpisces/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1732800607790-577850bd277aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1732800607790-577850bd277aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1732800607790-577850bd277aimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "piscesalan_",
      total_collections: 0,
      total_likes: 4,
      total_photos: 15,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "piscesalan_",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
];
