import {
  PAGE_HOME_STYLE_GALLERY_CONTAINER,
  PAGE_HOME_STYLE_GALLERY_IMAGE,
} from "@/pages/home/_const/style";

export const PAGE_BOOKMARK_STYLE_GALLERY_CONTAINER =
  PAGE_HOME_STYLE_GALLERY_CONTAINER;

export const PAGE_BOOKMARK_STYLE_GALLERY_IMAGE = PAGE_HOME_STYLE_GALLERY_IMAGE;
